services:
  logging-service:
    build: ./logging-service
    ports:
      - "8081:8081"
    networks:
      - banking

  counter-service:
    build: ./counter-service
    ports:
      - "8082:8082"
    networks:
      - banking

  facade-service:
    build: ./facade-service
    ports:
      - "8080:8080"
    depends_on:
      - logging-service
      - counter-service
    networks:
      - banking

networks:
  banking:
    driver: bridge
